name: python-app-build

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'main' 
  #   paths:
  #     - 'backend/**'
  #     - '.github/workflows/**'

jobs:
  build:
    # name: Checkout code
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          tags: nirajjn76/pythonflaskdemo:latest
          
